site_name: R15 Rover Docs
site_description: User & Safety Manual for the R15 Wildlife Monitoring Rover
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list

nav:
  - Introduction: index.md
  - Getting Started:
    - What You’ll Need: getting_started/requirements.md
    - First Time Setup:
      - Overview: getting_started/first_time_setup/overview.md
      - Control Laptop: getting_started/first_time_setup/control_laptop.md
      - Onboard Computer: getting_started/first_time_setup/onboard.md
      - Optional Server: getting_started/first_time_setup/server.md
      - Optional WiFi Extender: getting_started/first_time_setup/extend.md
      - Hardware: getting_started/first_time_setup/hardware_setup.md
  - Manuals:
    - Operation Manual: operation.md
    - Safety Manual: safety.md
    - Troubleshooting Manual: troubleshooting.md
